import type { ProviderId, ProviderMetadata } from './types';

export const PROVIDERS: Record<ProviderId, ProviderMetadata> = {
  claude: {
    id: 'claude',
    name: 'Claude',
    icon: 'Bot',
    accentColor: 'orange',
    authMethod: 'oauth',
    statusPageUrl: 'https://status.anthropic.com',
  },
  codex: {
    id: 'codex',
    name: 'Codex',
    icon: 'Sparkles',
    accentColor: 'green',
    authMethod: 'cli',
    statusPageUrl: 'https://status.openai.com',
  },
  cursor: {
    id: 'cursor',
    name: 'Cursor',
    icon: 'MousePointer',
    accentColor: 'purple',
    authMethod: 'cookies',
    statusPageUrl: 'https://status.cursor.sh',
  },
  copilot: {
    id: 'copilot',
    name: 'Copilot',
    icon: 'Github',
    accentColor: 'emerald',
    authMethod: 'oauth',
    statusPageUrl: 'https://www.githubstatus.com',
  },
  gemini: {
    id: 'gemini',
    name: 'Gemini',
    icon: 'Gem',
    accentColor: 'blue',
    authMethod: 'oauth',
  },
  antigravity: {
    id: 'antigravity',
    name: 'Antigravity',
    icon: 'Rocket',
    accentColor: 'cyan',
    authMethod: 'local_config',
  },
  factory: {
    id: 'factory',
    name: 'Factory',
    icon: 'Factory',
    accentColor: 'amber',
    authMethod: 'cookies',
  },
  zai: {
    id: 'zai',
    name: 'z.ai',
    icon: 'Zap',
    accentColor: 'yellow',
    authMethod: 'api_key',
  },
  minimax: {
    id: 'minimax',
    name: 'MiniMax',
    icon: 'Minimize2',
    accentColor: 'rose',
    authMethod: 'cookies',
  },
  kimi: {
    id: 'kimi',
    name: 'Kimi',
    icon: 'Moon',
    accentColor: 'indigo',
    authMethod: 'cookies',
  },
  kimi_k2: {
    id: 'kimi_k2',
    name: 'Kimi K2',
    icon: 'Moon',
    accentColor: 'violet',
    authMethod: 'api_key',
  },
  kiro: {
    id: 'kiro',
    name: 'Kiro',
    icon: 'Terminal',
    accentColor: 'teal',
    authMethod: 'cli',
  },
  vertex: {
    id: 'vertex',
    name: 'Vertex AI',
    icon: 'Cloud',
    accentColor: 'sky',
    authMethod: 'oauth',
  },
  augment: {
    id: 'augment',
    name: 'Augment',
    icon: 'Plus',
    accentColor: 'lime',
    authMethod: 'cookies',
  },
  amp: {
    id: 'amp',
    name: 'Amp',
    icon: 'Volume2',
    accentColor: 'pink',
    authMethod: 'cookies',
  },
  jetbrains: {
    id: 'jetbrains',
    name: 'JetBrains AI',
    icon: 'Code',
    accentColor: 'fuchsia',
    authMethod: 'local_config',
  },
  opencode: {
    id: 'opencode',
    name: 'OpenCode',
    icon: 'Terminal',
    accentColor: 'slate',
    authMethod: 'cookies',
  },
};

export const DEFAULT_ENABLED_PROVIDERS: ProviderId[] = [];

export const DEFAULT_SETTINGS = {
  refreshIntervalSeconds: 300,
  enabledProviders: DEFAULT_ENABLED_PROVIDERS,
  providerOrder: Object.keys(PROVIDERS) as ProviderId[],
  displayMode: 'merged' as const,
  showNotifications: true,
  launchAtLogin: false,
  showCredits: true,
  showCost: true,
};
