import type { ProviderId, ProviderMetadata, CookieSource } from './types';

export const PROVIDERS: Record<ProviderId, ProviderMetadata> = {
  claude: {
    id: 'claude',
    name: 'Claude',
    icon: 'Bot',
    accentColor: 'orange',
    authMethod: 'oauth',
    sessionLabel: 'Session',
    weeklyLabel: 'Weekly',
    opusLabel: 'Sonnet',
    supportsOpus: true,
    supportsCredits: false,
    implemented: true,
    statusPageUrl: 'https://status.anthropic.com',
  },
  codex: {
    id: 'codex',
    name: 'Codex',
    icon: 'Sparkles',
    accentColor: 'green',
    authMethod: 'cli',
    sessionLabel: 'Session',
    weeklyLabel: 'Weekly',
    opusLabel: null,
    supportsOpus: false,
    supportsCredits: true,
    implemented: true,
    statusPageUrl: 'https://status.openai.com',
  },
  cursor: {
    id: 'cursor',
    name: 'Cursor',
    icon: 'MousePointer',
    accentColor: 'purple',
    authMethod: 'cookies',
    sessionLabel: 'Plan',
    weeklyLabel: 'On-Demand',
    opusLabel: null,
    supportsOpus: false,
    supportsCredits: true,
    implemented: true,
    statusPageUrl: 'https://status.cursor.sh',
  },
  copilot: {
    id: 'copilot',
    name: 'Copilot',
    icon: 'Github',
    accentColor: 'emerald',
    authMethod: 'oauth',
    sessionLabel: 'Premium',
    weeklyLabel: 'Chat',
    opusLabel: null,
    supportsOpus: false,
    supportsCredits: false,
    implemented: true,
    statusPageUrl: 'https://www.githubstatus.com',
  },
  gemini: {
    id: 'gemini',
    name: 'Gemini',
    icon: 'Gem',
    accentColor: 'blue',
    authMethod: 'oauth',
    sessionLabel: 'Pro',
    weeklyLabel: 'Flash',
    opusLabel: null,
    supportsOpus: false,
    supportsCredits: false,
    implemented: true,
  },
  antigravity: {
    id: 'antigravity',
    name: 'Antigravity',
    icon: 'Rocket',
    accentColor: 'cyan',
    authMethod: 'local_config',
    sessionLabel: 'Claude',
    weeklyLabel: 'Gemini Pro',
    opusLabel: 'Gemini Flash',
    supportsOpus: true,
    supportsCredits: false,
    implemented: true,
    statusPageUrl: 'https://www.google.com/appsstatus/dashboard/products/npdyhgECDJ6tB66MxXyo',
  },
  factory: {
    id: 'factory',
    name: 'Droid',
    icon: 'Factory',
    accentColor: 'amber',
    authMethod: 'cookies',
    sessionLabel: 'Standard',
    weeklyLabel: 'Premium',
    opusLabel: null,
    supportsOpus: false,
    supportsCredits: false,
    implemented: true,
  },
  zai: {
    id: 'zai',
    name: 'z.ai',
    icon: 'Zap',
    accentColor: 'yellow',
    authMethod: 'api_key',
    sessionLabel: 'Tokens',
    weeklyLabel: 'MCP',
    opusLabel: null,
    supportsOpus: false,
    supportsCredits: false,
    implemented: true,
  },
  minimax: {
    id: 'minimax',
    name: 'MiniMax',
    icon: 'Minimize2',
    accentColor: 'rose',
    authMethod: 'cookies',
    sessionLabel: 'Prompts',
    weeklyLabel: 'Window',
    opusLabel: null,
    supportsOpus: false,
    supportsCredits: true,
    implemented: true,
  },
  kimi: {
    id: 'kimi',
    name: 'Kimi',
    icon: 'Moon',
    accentColor: 'indigo',
    authMethod: 'cookies',
    sessionLabel: 'Weekly',
    weeklyLabel: 'Rate Limit',
    opusLabel: null,
    supportsOpus: false,
    supportsCredits: false,
    implemented: true,
  },
  kimi_k2: {
    id: 'kimi_k2',
    name: 'Kimi K2',
    icon: 'Moon',
    accentColor: 'violet',
    authMethod: 'api_key',
    sessionLabel: 'Credits',
    weeklyLabel: 'Credits',
    opusLabel: null,
    supportsOpus: false,
    supportsCredits: false,
    implemented: true,
  },
  kiro: {
    id: 'kiro',
    name: 'Kiro',
    icon: 'Terminal',
    accentColor: 'teal',
    authMethod: 'cli',
    sessionLabel: 'Credits',
    weeklyLabel: 'Bonus',
    opusLabel: null,
    supportsOpus: false,
    supportsCredits: false,
    implemented: true,
    statusPageUrl: 'https://status.aws.amazon.com/rss/all.rss',
  },
  vertexai: {
    id: 'vertexai',
    name: 'Vertex AI',
    icon: 'Cloud',
    accentColor: 'sky',
    authMethod: 'oauth',
    sessionLabel: 'Requests',
    weeklyLabel: 'Tokens',
    opusLabel: null,
    supportsOpus: false,
    supportsCredits: false,
    implemented: false,
  },
  augment: {
    id: 'augment',
    name: 'Augment',
    icon: 'Plus',
    accentColor: 'lime',
    authMethod: 'cookies',
    sessionLabel: 'Credits',
    weeklyLabel: 'Usage',
    opusLabel: null,
    supportsOpus: false,
    supportsCredits: true,
    implemented: true,
  },
  amp: {
    id: 'amp',
    name: 'Amp',
    icon: 'Volume2',
    accentColor: 'pink',
    authMethod: 'cookies',
    sessionLabel: 'Amp Free',
    weeklyLabel: 'Balance',
    opusLabel: null,
    supportsOpus: false,
    supportsCredits: false,
    implemented: true,
  },
  jetbrains: {
    id: 'jetbrains',
    name: 'JetBrains AI',
    icon: 'Code',
    accentColor: 'fuchsia',
    authMethod: 'local_config',
    sessionLabel: 'Current',
    weeklyLabel: 'Refill',
    opusLabel: null,
    supportsOpus: false,
    supportsCredits: true,
    implemented: true,
  },
  opencode: {
    id: 'opencode',
    name: 'OpenCode',
    icon: 'Terminal',
    accentColor: 'slate',
    authMethod: 'cookies',
    sessionLabel: '5-hour',
    weeklyLabel: 'Weekly',
    opusLabel: null,
    supportsOpus: false,
    supportsCredits: false,
    implemented: true,
  },
  synthetic: {
    id: 'synthetic',
    name: 'Synthetic',
    icon: 'Sparkle',
    accentColor: 'emerald',
    authMethod: 'api_key',
    sessionLabel: 'Quota',
    weeklyLabel: 'Usage',
    opusLabel: null,
    supportsOpus: false,
    supportsCredits: false,
    implemented: true,
  },
};

export const DEFAULT_ENABLED_PROVIDERS: ProviderId[] = [];

export const DEFAULT_SETTINGS = {
  refreshIntervalSeconds: 300,
  enabledProviders: DEFAULT_ENABLED_PROVIDERS,
  providerOrder: Object.keys(PROVIDERS) as ProviderId[],
  displayMode: 'merged' as const,
  menuBarDisplayMode: 'session' as const,
  usageBarDisplayMode: 'remaining' as const,
  resetTimeDisplayMode: 'relative' as const,
  showNotifications: true,
  notifySessionUsage: true,
  notifyCreditsLow: true,
  notifyRefreshFailure: true,
  notifyStaleUsage: true,
  launchAtLogin: false,
  showCredits: true,
  showCost: true,
  showExtraUsage: true,
  cookieSources: {} as Partial<Record<ProviderId, CookieSource>>,
  debugFileLogging: false,
  debugKeepCliSessionsAlive: false,
  debugRandomBlink: false,
};
